language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
- yarn
script: yarn test

